# fly.toml file generated for dawn-fire-4570 on 2023-02-12T23:53:20+01:00

app = "dawn-fire-4570"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
builder = "paketobuildpacks/builder:tiny"
#buildpacks = ["gcr.io/paketo-buildpacks/java-native-image"]

[build.args]
BP_JVM_VERSION=17
BP_GRADLE_BUILD_ARGUMENTS="--no-daemon nativeCompile"
BP_NATIVE_IMAGE=true
path="."

[env]
PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
